// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DvLyon_Core","status":true,"description":"Core Functions","parameters":{"SkipTitle":"true","OpenTools":"true"}}
];
