// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DvLyon_Core","status":true,"description":"Core Functions","parameters":{"SkipTitle":"true","OpenTools":"true"}},
{"name":"DvLyon_StatsTracker","status":true,"description":"Core Functions","parameters":{"SkipTitle":"false","OpenTools":"false"}}
];
